<?php
/**
 * 
 *
 * @category Mygento
 * @package Mygento_Payture
 * @copyright Copyright © 2015 NKS LLC. (http://www.mygento.ru)
 */

?>
<strong><?php echo $this->getPaytureName(); ?></strong>
<?php if ($this->getOrder()): ?>
    <?php
    $state = $this->getOrder()->getState();
    if (!$this->isPaid() && $payture_state != 'Authorized' && $state != 'complete' && $state != 'closed' && $state != 'canceled'):

        ?>
        <p><a target="_blank" href="<?php echo $this->getPaylink(); ?>">Оплатить заказ</a></p>
    <?php endif; ?>
<?php endif; ?>