<?php
/**
 * 
 *
 * @category Mygento
 * @package Mygento_Payture
 * @copyright 2017 NKS LLC. (https://www.mygento.ru)
 */
?>
<strong><?php echo $this->getPaytureName(); ?></strong>
<?php $payture_state = $this->getState(); ?>
<?php if ($this->getOrder()): ?>
    <?php
    $state = $this->getOrder()->getState();
    if (!$this->isPaid() && $payture_state != 'Authorized' && $state != 'complete' && $state != 'closed' && $state != 'canceled'):
        ?>
        <p><a target="_blank" href="<?php echo $this->getPaylink(); ?>">Оплатить заказ</a></p>
    <?php endif; ?>
<?php endif; ?>
